[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
sender = "0x0f14341A7f464320319025540E8Fe48Ad0fe5aec"
force = true
optimizer = true
auto_detect_remappings = false
optimizer_runs = 9999
evm_version = "cancun"
bytecode_hash = "ipfs"
extra_output_files = ["metadata"]
eth_rpc_url  = "https://erpc.ringdao.com/main/evm/8453"
